language: python
python:
- 2.7
- 3.4
before_install:
- pip install -r requires/testing.txt
install:
- pip install -e .
script: nosetests
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: sprockets
  password:
    secure: ARvFw5CHqQZqPOkJXxQSe7EAEbX1yt7FiBTtzz8Gd6XndbY10HVCSWhGYeldm9LevvQc9p77pBEvsl+bXGQbJ3NW/r/U5PADaFdmi4bxmXN8yc+dFKzn72MpZfL+kCV2T/HutuOY6dQa4okTkKVV+sqwPLKPhL69zH/PxQg8qe4=
  on:
    python: 3.4
    tags: true
    all_branches: true
